### ISSUE TITLE
Decode algorithm？

### ISSUE THREAD

**Issue by zwhe99** [templexxx/xorsimd#8]
Hi~

I can't find the decoding algorithm in the code, how should I perform the decode?

**Comment by templexxx** [comment]
> Hi~
> 
> I can't find the decoding algorithm in the code, how should I perform the decode?

For XOR, encode is as same as decode

Encode:

A  ⊕ B = C

Decode:

B  ⊕ C = A

A  ⊕ C = B

 ⊕  is XOR

**Comment by zwhe99** [comment]
> > Hi~
> > I can't find the decoding algorithm in the code, how should I perform the decode?
> 
> For XOR, encode is as same as decode
> 
> Encode:
> 
> A ⊕ B = C
> 
> Decode:
> 
> B ⊕ C = A
> 
> A ⊕ C = B
> 
> ⊕ is XOR

I get it. Thanks!
